### ISSUE TITLE
Support for preloading associations?

### ISSUE THREAD

**Issue by MarbilleJuntado** [coryodaniel/arbor#22]
I want to be able to do something like:
`folder |> Folder.descendants(preload: [:contracts]) |> Repo.all`

Right now, I'm using the following solution:
`folder |> Folder.descendants |> Repo.all |> Enum.map(&Repo.preload(&1, [:contracts]))`
which looks very hack-y.

**Comment by coryodaniel** [comment]
`descendants` should return a query, does the following work?

```elixir
folder |> Folder.descendants() |> Repo.all(preload: [:comments])
```

**Comment by coryodaniel** [comment]
Do either of these work?

`folder |> Folder.descendants() |> Repo.preload([:contracts])`

`folder |> Folder.descendants() |> Ecto.Query.preload([:contracts])`
